name: License Check

on: [pull_request]

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Licensed CI
        uses: github/licensed-ci@v1.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
